## Parameters for featurewise standarization

In [1]:
import CCAugmentation as cca
from datasets.SHHB.setting import cfg_data
from load_data import CustomDataset
import CCAugmentation.transformations as ccat
import numpy as np
from tqdm import tqdm_notebook
import tqdm

In [2]:
imgs, _ = cca.Pipeline(
        cca.examples.loading.SHHLoader("/dataset/ShanghaiTech", "train", "B"), [
            ccat.Normalize("range_0_to_1")
        ]
    ).execute_collect()

100%|█████████▉| 399/400 [00:06<00:00, 67.14it/s]

In [3]:
print(np.mean(imgs))
print(np.std(imgs))
print(np.mean(imgs, (0, 1, 2)))
print(np.std(imgs, (0, 1, 2)))

0.44337569764081153
0.2312020086228266


100%|██████████| 400/400 [00:19<00:00, 67.14it/s]

[0.43153972 0.44694245 0.45164492]
[0.22612214 0.22956612 0.23729746]


In [4]:
imgs, _ = cca.Pipeline(
        cca.examples.loading.SHHLoader("/dataset/ShanghaiTech", "train", "B"), [
        ]
    ).execute_collect()


 98%|█████████▊| 391/400 [00:04<00:00, 100.86it/s]

In [5]:
print(np.mean(imgs))
print(np.std(imgs))
print(np.mean(imgs, (0, 1, 2)))
print(np.std(imgs, (0, 1, 2)))

113.06080289840698
58.956512198820526
[110.0426287  113.97032411 115.16945588]



100%|██████████| 400/400 [00:14<00:00, 100.86it/s]

[57.66114641 58.53936174 60.51085266]
