In [ ]:
import os
import random
import torch
import torchvision.transforms as standard_transforms
import scipy.io as sio
import matplotlib
import pandas as pd
import misc.transforms as own_transforms
import warnings

from torch.autograd import Variable
from torch.utils.data import DataLoader
from PIL import Image, ImageOps
from matplotlib import pyplot as plt
from tqdm import trange, tqdm
from misc.utils import *
from models.CC import CrowdCounter
from config import cfg
import CCAugmentation as cca
from datasets.SHHB.setting import cfg_data
from load_data import CustomDataset
import CCAugmentation.transformations as ccat

torch.cuda.set_device(0)
torch.backends.cudnn.benchmark = True
warnings.filterwarnings('ignore')

mean_std = ([0.452016860247, 0.447249650955, 0.431981861591],[0.23242045939, 0.224925786257, 0.221840232611])

img_transform = standard_transforms.Compose([
        standard_transforms.ToTensor(),
        standard_transforms.Normalize(*mean_std)
    ])
restore = standard_transforms.Compose([
        own_transforms.DeNormalize(*mean_std),
        standard_transforms.ToPILImage()
    ])
pil_to_tensor = standard_transforms.ToTensor()

In [ ]:
val_pipeline = cca.Pipeline(
        cca.examples.loading.SHHLoader("/dataset/ShanghaiTech", "test", "B"), [
            ccat.Normalize("featurewise_centering", by_channel=True, means=[107.39323323, 111.061098,   112.03879525]),
            ccat.Normalize("featurewise_std_normalization", by_channel=True, stds=[57.61469767, 58.51149575, 60.53830933])
        ]
    ).execute_generate()
val_loader = DataLoader(CustomDataset(val_pipeline), batch_size=cfg_data.VAL_BATCH_SIZE, num_workers=1, drop_last=False)

val_img = list(val_loader)

In [ ]:
# model_path = './exp/11-26_06-00_SHHB_MCNN_0.0001_[noAug]/all_ep_146_mae_23.91_mse_35.70.pth'
# model_path = './exp/11-26_06-57_SHHB_MCNN_0.0001_[noAug]/all_ep_175_mae_17.92_mse_26.94.pth'
# model_path = './exp/11-26_07-42_SHHB_MCNN_0.0001_[noAug]/all_ep_171_mae_18.16_mse_29.66.pth'
# model_path = './exp/11-27_09-59_SHHB_MCNN_0.0001_[flipLR]/all_ep_180_mae_18.34_mse_30.49.pth'
# model_path = './exp/11-27_10-44_SHHB_MCNN_0.0001_[flipLR]/all_ep_181_mae_19.11_mse_33.26.pth'
# model_path = './exp/11-27_11-30_SHHB_MCNN_0.0001_[flipLR]/all_ep_180_mae_18.16_mse_30.61.pth'
# model_path = './exp/11-27_17-48_SHHB_MCNN_0.0001_[crop4]/all_ep_168_mae_17.00_mse_29.09.pth'
# model_path = './exp/11-27_18-18_SHHB_MCNN_0.0001_[crop4]/all_ep_168_mae_19.30_mse_35.17.pth'
# model_path = './exp/11-27_18-48_SHHB_MCNN_0.0001_[crop4]/all_ep_168_mae_20.61_mse_35.46.pth'
# model_path = './exp/11-27_19-34_SHHB_MCNN_0.0001_[crop2]/all_ep_155_mae_22.83_mse_42.29.pth'
# model_path = './exp/11-27_20-08_SHHB_MCNN_0.0001_[crop2]/all_ep_155_mae_24.00_mse_44.81.pth'
# model_path = './exp/11-27_20-42_SHHB_MCNN_0.0001_[crop2]/all_ep_155_mae_22.42_mse_42.58.pth'
# model_path = './exp/11-27_22-04_SHHB_MCNN_0.0001_[rotate30]/all_ep_200_mae_19.48_mse_30.50.pth'
# model_path = './exp/11-28_00-16_SHHB_MCNN_0.0001_[rotate30]/all_ep_200_mae_21.60_mse_33.60.pth'
# model_path = './exp/11-28_02-27_SHHB_MCNN_0.0001_[rotate30]/all_ep_200_mae_20.54_mse_31.20.pth'
# model_path = './exp/11-28_06-38_SHHB_MCNN_0.0001_[rotate10]/all_ep_170_mae_21.30_mse_35.58.pth'
# model_path = './exp/11-28_08-49_SHHB_MCNN_0.0001_[rotate10]/all_ep_200_mae_20.20_mse_34.59.pth'
# model_path = './exp/11-28_11-00_SHHB_MCNN_0.0001_[rotate10]/all_ep_172_mae_19.22_mse_36.34.pth'
# model_path = './exp/11-28_16-20_SHHB_MCNN_0.0001_[norm]/all_ep_200_mae_33.06_mse_48.00.pth'
# model_path = './exp/11-28_17-05_SHHB_MCNN_0.0001_[norm]/all_ep_200_mae_33.05_mse_48.01.pth'
# model_path = './exp/11-28_17-51_SHHB_MCNN_0.0001_[norm]/all_ep_200_mae_33.06_mse_48.01.pth'
# model_path = './exp/11-28_18-54_SHHB_MCNN_0.0001_[sampleWise]/all_ep_145_mae_40.14_mse_65.59.pth'
# model_path = './exp/11-29_04-46_SHHB_MCNN_0.0001_[gray]/all_ep_121_mae_34.20_mse_52.37.pth'
# model_path = './exp/11-29_05-24_SHHB_MCNN_0.0001_[gray]/all_ep_121_mae_34.45_mse_54.12.pth'
# model_path = './exp/11-29_06-02_SHHB_MCNN_0.0001_[gray]/all_ep_108_mae_35.26_mse_53.38.pth'
# model_path = './exp/12-03_05-30_SHHB_MCNN_0.0001_[flip+crop]/all_ep_603_mae_18.77_mse_35.42.pth'
# model_path = './exp/12-03_06-54_SHHB_MCNN_0.0001_[cutout5]/all_ep_183_mae_19.09_mse_28.35.pth'
# model_path = './exp/12-03_07-40_SHHB_MCNN_0.0001_[cutout5]/all_ep_170_mae_18.66_mse_28.93.pth'
# model_path = './exp/12-03_08-25_SHHB_MCNN_0.0001_[cutout5]/all_ep_174_mae_18.79_mse_29.10.pth'
# model_path = './exp/12-03_09-11_SHHB_MCNN_0.0001_[FW]/all_ep_179_mae_22.99_mse_38.61.pth'
# model_path = './exp/12-03_10-35_SHHB_MCNN_0.0001_[FW]/all_ep_179_mae_23.08_mse_38.69.pth'
model_path = './exp/12-03_12-00_SHHB_MCNN_0.0001_[FW]/all_ep_179_mae_23.77_mse_40.57.pth'

net = CrowdCounter(cfg.GPU_ID,cfg.NET)
net.load_state_dict(torch.load(model_path))
net.cuda()
net.eval()
print("Model loaded.")

In [ ]:
start = 0
N = 3

for vi, data in enumerate(val_img[start:start+N], 0):
    img, gt_map = data

    with torch.no_grad():
        img = Variable(img).cuda()
        pred_map = net.test_forward(img)
        pred_map = pred_map.data.cpu().numpy()
        
    new_img = img.data.cpu().numpy()
    new_img = np.moveaxis(new_img, 1, 2)
    new_img = np.moveaxis(new_img, 2, 3)
    new_img = np.squeeze(new_img)[:,:,::-1]
#     new_img = np.squeeze(new_img)[:,::-1]
    
    pred_cnt = np.sum(pred_map[0])/100.0
    gt_count = np.sum(gt_map.data.cpu().numpy())/100.0
    
    fg, (ax0, ax1, ax2) = plt.subplots(1, 3, figsize=(16, 5))
    plt.suptitle(' '.join([
            'count_label:', str(round(gt_count, 3)),
            'count_prediction:', str(round(pred_cnt, 3))
        ]))
    ax0.imshow(np.uint8(new_img))
#     ax0.imshow(np.uint8(new_img), cmap='gray')
    ax1.imshow(np.squeeze(gt_map), cmap='jet')
    ax2.imshow(np.squeeze(pred_map), cmap='jet')
    plt.show()
    
#     fg, (ax0, ax1) = plt.subplots(1, 2, figsize=(16, 5))
#     plt.suptitle(' '.join([
#             'count_label:', str(round(gt_count, 3))
#         ]))
#     ax0.imshow(np.uint8(new_img))
#     ax1.imshow(np.squeeze(gt_map), cmap='jet')
#     plt.show()
    
#     fg.savefig("fg.png")

In [ ]:
mae = np.empty(len(val_img))
mse = np.empty(len(val_img))
for vi, data in enumerate(tqdm(val_img), 0):
    img, gt_map = data

    with torch.no_grad():
        img = Variable(img).cuda()
        pred_map = net.test_forward(img)
        pred_map = pred_map.data.cpu().numpy()
    
    pred_cnt = np.sum(pred_map[0])/100.0
    gt_count = np.sum(gt_map.data.cpu().numpy())/100.0
    mae[vi] = np.abs(gt_count-pred_cnt)
    mse[vi] = (gt_count-pred_cnt)**2
    
print('MAE:', round(mae.mean(),2))
print('MSE:', round(np.sqrt(mse.mean()),2))

## Parameters for featurewise standarization

In [3]:
import CCAugmentation as cca
from datasets.SHHB.setting import cfg_data
from load_data import CustomDataset
import CCAugmentation.transformations as ccat
import numpy as np
from tqdm import tqdm_notebook
import tqdm

In [8]:
imgs, _ = cca.Pipeline(
        cca.examples.loading.SHHLoader("/dataset/ShanghaiTech", "train", "B"), [
            ccat.Normalize("range_0_to_1")
        ]
    ).execute_collect()



  0%|          | 0/400 [00:00<?, ?it/s]

  2%|▏         | 7/400 [00:00<00:05, 66.26it/s]

  4%|▎         | 14/400 [00:00<00:05, 67.21it/s]

  5%|▌         | 21/400 [00:00<00:05, 67.41it/s]

  7%|▋         | 28/400 [00:00<00:05, 67.73it/s]

  9%|▉         | 35/400 [00:00<00:05, 68.32it/s]

 10%|█         | 42/400 [00:00<00:05, 68.19it/s]

 12%|█▏        | 49/400 [00:00<00:05, 68.17it/s]

 14%|█▍        | 56/400 [00:00<00:05, 67.67it/s]

 16%|█▌        | 63/400 [00:00<00:05, 67.40it/s]

 18%|█▊        | 71/400 [00:01<00:04, 67.73it/s]

 20%|█▉        | 78/400 [00:01<00:04, 67.75it/s]

 21%|██▏       | 85/400 [00:01<00:04, 67.83it/s]

 23%|██▎       | 92/400 [00:01<00:04, 68.05it/s]

 25%|██▍       | 99/400 [00:01<00:04, 67.52it/s]

 26%|██▋       | 106/400 [00:01<00:04, 66.10it/s]

 28%|██▊       | 113/400 [00:01<00:04, 67.00it/s]

 30%|███       | 120/400 [00:01<00:04, 67.09it/s]

 32%|███▏      | 127/400 [00:01<00:04, 67.43it/s]

 34%|███▎      | 134/400 [00:01<00:03, 68.08it/s]

 35

In [9]:
print(np.mean(imgs))
print(np.std(imgs))
print(np.mean(imgs, (0, 1, 2)))
print(np.std(imgs, (0, 1, 2)))

0.44337569764081153
0.2312020086228266
[0.43153972 0.44694245 0.45164492]




100%|██████████| 400/400 [00:21<00:00, 72.12it/s]

[0.22612214 0.22956612 0.23729746]


In [ ]:
imgs, _ = cca.Pipeline(
        cca.examples.loading.SHHLoader("/dataset/ShanghaiTech", "train", "B"), [
        ]
    ).execute_collect()

In [6]:
print(np.mean(imgs))
print(np.std(imgs))
print(np.mean(imgs, (0, 1, 2)))
print(np.std(imgs, (0, 1, 2)))

113.06080289840698
58.956512198820526
[110.0426287  113.97032411 115.16945588]
[57.66114641 58.53936174 60.51085266]
